name = "sitemap-diff"
main = "src/index.ts"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

# 定义持久化存储
[durable_objects]
bindings = [
  { name = "RSS_STORAGE", class_name = "RSSStorage" }
]

# 添加 Durable Objects 迁移配置
[[migrations]]
tag = "v1"
new_classes = ["RSSStorage"]

# 定义KV存储（用于存储sitemap数据）
[[kv_namespaces]]
binding = "SITEMAP_KV"
# 在实际部署时需要替换为您的KV命名空间ID
id =62d5ca0ba86c4dd5bcdc8888df41eace

# 定义环境变量
[vars]
# 这些变量会在部署时从 .env 或 Cloudflare Dashboard 中获取
TELEGRAM_BOT_TOKEN = ""
TELEGRAM_TARGET_CHAT = ""

# 定义定时任务（每小时执行一次）
[triggers]
crons = ["0 * * * *"] 